-- Q1
SELECT NAME FROM EMP E WHERE SALARY > (SELECT AVG(SALARY) FROM EMP GROUP BY DEPTNO HAVING DEPTNO = E.DEPTNO);

-- Q2
SELECT EMPNO, NAME, ADD_MONTHS(TO_DATE(HIREDATE, 'YYYY-MM-DD'), 30*12) RETIREDATE FROM EMP;

-- Q3
SELECT 'EMPLOYEE ' || NAME || ' WORKS IN ' || DNAME || ' AND HAS A SALARY OF ' || SALARY SENTENCE FROM EMP NATURAL JOIN DEPT;

-- Q4
SELECT * FROM EMP WHERE JOB <> 'MANAGER';

-- Q5
SELECT * FROM EMP WHERE SALARY+NVL(COMM, 0) > 4000;

-- Q6
SELECT NAME, SALARY, NVL(COMM, 0)*0.1 BONUS FROM EMP;

-- Q7
-- X = 'MILLER' (7934)
SELECT * FROM EMP 
WHERE 
SALARY > (SELECT SALARY FROM EMP WHERE EMPNO = 7934) AND
DEPTNO <> (SELECT DEPTNO FROM EMP WHERE EMPNO = 7934);

-- Q8
SELECT NAME, (SYSDATE-TO_DATE(HIREDATE, 'YYYY-MM-DD'))/365 EXP FROM EMP;

-- Q9
SELECT DEPTNO, MAX(SALARY)-MIN(SALARY) FROM EMP GROUP BY DEPTNO HAVING MAX(SALARY)-MIN(SALARY) < 1000;

-- Q10
SELECT * FROM EMP WHERE NAME LIKE '%R%_%R%';

-- Q11
SELECT * FROM EMP WHERE SALARY = (SELECT MAX(SALARY) FROM EMP WHERE SALARY <> (SELECT MAX(SALARY) FROM EMP));
SELECT * FROM EMP WHERE SALARY = (SELECT MAX(SALARY) FROM (SELECT SALARY FROM EMP MINUS SELECT MAX(SALARY) FROM EMP));

-- Q12
SELECT DEPTNO, DNAME, COUNT(DISTINCT JOB) FROM EMP NATURAL JOIN DEPT GROUP BY DEPTNO, DNAME;

-- Q13
SELECT E.NAME, E.BOSS, F.NAME BOSSNAME, F.SALARY-E.SALARY DIFF FROM EMP E INNER JOIN EMP F ON E.BOSS = F.EMPNO;

-- Q14
-- X = ALLEN (7499)
SELECT AVG(SALARY) FROM EMP GROUP BY JOB HAVING JOB = (SELECT JOB FROM EMP WHERE EMPNO = 7499);

-- Q15
-- AMBIGUOUS

-- Q16
-- X = SCOTT (7788)
SELECT * FROM EMP E WHERE DEPTNO <> (SELECT DEPTNO FROM EMP WHERE EMPNO = 7788) AND SALARY < (SELECT AVG(SALARY) FROM EMP GROUP BY DEPTNO HAVING DEPTNO = E.DEPTNO);

-- Q17
-- ALLEN 7499
SELECT * FROM EMP WHERE SALARY+NVL(COMM, 0) > (SELECT SALARY+NVL(COMM, 0) FROM EMP WHERE EMPNO = 7499) AND HIREDATE > (SELECT HIREDATE FROM EMP WHERE EMPNO = 7499);

-- Q18
-- 10, 20
(SELECT DISTINCT JOB FROM EMP WHERE DEPTNO = 10) INTERSECT (SELECT DISTINCT JOB FROM EMP WHERE DEPTNO = 20);

-- Q19
SELECT NAME, SALARY FROM EMP;

-- Q20
SELECT DEPTNO, COUNT(*) FROM EMP WHERE JOB = 'MANAGER' GROUP BY DEPTNO;