-- Q1
-- raise sal by 10% if salesman, and log it
DROP TABLE MYEMP;
DROP TABLE MYEMP_LOG;

CREATE TABLE MYEMP AS (SELECT * FROM EMP);
CREATE TABLE MYEMP_LOG (
  EMPNO NUMBER(38, 0),
  NAME VARCHAR2(10 BYTE),
  PREVSAL NUMBER(7, 2),
  NEWSAL NUMBER(7, 2)
);

-- TRIGGERS
-- Q2
-- trigger FILL_AREA works for RECTANGLES

CREATE TABLE RECTANGLES (
  LENGTH NUMBER(7,2),
  BREADTH NUMBER(7,2),
  AREA NUMBER(16,2)
);


-- Q3
-- salesman_comm

CREATE TABLE SALESMAN_COMM (
  SNO NUMBER,
  SNAME VARCHAR2(30),
  JOINDATE DATE,
  BASIC NUMBER,
  COMM NUMBER
);

CREATE TABLE SALESMAN_LOG (
  SNO NUMBER,
  UPDATE_DATE DATE
);

-- Q4
-- FULL NAME

CREATE TABLE XYZ (
  FNAME VARCHAR2(30),
  MNAME VARCHAR2(30),
  LNAME VARCHAR2(30),
  FULLNAME VARCHAR2(62)
);

-- FUNCTIONS, PROCEDURES
-- Q5
-- myemp, dept if dept sal < 7500
DROP TABLE MYEMP;

CREATE TABLE MYEMP AS (SELECT * FROM EMP);
SELECT SUM(SALARY) FROM MYEMP GROUP BY DEPTNO;
SELECT DEPT_SAL(10) FROM DUAL;

-- Q6
-- product_master and reorder_master
DROP TABLE PRODUCT_MASTER;
DROP TABLE REORDER_MASTER;

CREATE TABLE PRODUCT_MASTER (
  PRODNAME VARCHAR2(30),
  CURRQUANTITY NUMBER,
  MAXQUANTITY NUMBER,
  LASTORDERDATE DATE,
  UNITPRICE NUMBER
);

CREATE TABLE REORDER_MASTER (
  PRODNAME VARCHAR2(30),
  REORDERDATE DATE,
  QUANTITY NUMBER
);

-- Q7
-- mgrinfo table
DROP TABLE MGRINFO;

CREATE TABLE MGRINFO (
  MGRNAME VARCHAR2(10 BYTE),
  TOTAL_SAL NUMBER(8, 2),
  AVG_SAL NUMBER(7, 2)
);





