DECLARE
  CURSOR C IS (SELECT * FROM EMP);
  TOTALSAL NUMBER;
  AVGSAL NUMBER;
  CNT NUMBER;
BEGIN
  FOR X IN C
  LOOP
    IF (X.JOB = 'MANAGER') THEN
      TOTALSAL := 0;
      CNT := 0;
      FOR Y IN (SELECT * FROM EMP WHERE BOSS = X.EMPNO)
      LOOP
        TOTALSAL := TOTALSAL+Y.SALARY;
        CNT := CNT+1;
      END LOOP;
      AVGSAL := TOTALSAL/CNT;
      INSERT INTO MGRINFO VALUES (X.NAME, TOTALSAL, AVGSAL); 
    END IF;
  END LOOP;
END;