SET SERVEROUTPUT ON;
DECLARE
  USR MYEMP.EMPNO%TYPE;
  J MYEMP.JOB%TYPE;
  OLDSAL MYEMP.SALARY%TYPE;
  NM MYEMP.NAME%TYPE;
BEGIN
  USR := &EMP_NO_PLEASE_;
  SELECT JOB, SALARY, NAME INTO J, OLDSAL, NM FROM EMP WHERE EMPNO = USR;
  IF (J <> 'SALESMAN') THEN
    UPDATE MYEMP SET SALARY = OLDSAL*1.1 WHERE EMPNO = USR;
    DBMS_OUTPUT.PUT_LINE('UPDATED FOR ' || NM);
    INSERT INTO MYEMP_LOG VALUES (USR, NM, OLDSAL, OLDSAL*1.1);  
  END IF;
END;