DECLARE
  CURSOR C IS (SELECT * FROM EMP);
BEGIN
  FOR X IN C
  LOOP
    IF (IS_SALESMAN(X.JOB) = 0) THEN
      UPDATE MYEMP SET SALARY = X.SALARY*1.1 WHERE EMPNO = X.EMPNO;
      DBMS_OUTPUT.PUT_LINE('UPDATE DONE FOR ' || X.NAME);
      INSERT INTO MYEMP_LOG VALUES (X.EMPNO, X.NAME, X.SALARY, X.SALARY*1.1);
    END IF;
  END LOOP;
END;